SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `monitorsensors` DEFAULT CHARACTER SET utf8;
USE `monitorsensors`;

CREATE TABLE IF NOT EXISTS TYPE (
type VARCHAR(30) NOT NULL,
PRIMARY KEY (type)
);

INSERT INTO TYPE (type) VALUE ("Pressure"), ("Voltage"), ("Temperature"), ("Humidity");

CREATE TABLE IF NOT EXISTS UNIT (
unit VARCHAR(30) NOT NULL,
PRIMARY KEY (unit)
);

INSERT INTO UNIT (unit) VALUE ("bar"), ("voltage"), ("°С"), ("%");

CREATE TABLE IF NOT EXISTS SENSORS (
id  BIGINT AUTO_INCREMENT NOT NULL,
title VARCHAR(30) NOT NULL,
model VARCHAR(15) NOT NULL,
range_from INT NOT NULL,
range_to INT NOT NULL,
type VARCHAR(30) NOT NULL,
unit VARCHAR(30),
location VARCHAR(10),
description VARCHAR(200),

PRIMARY KEY (id),
FOREIGN KEY (type) REFERENCES TYPE (type),
FOREIGN KEY (unit) REFERENCES UNIT (unit)
) AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS USERS (
id BIGINT AUTO_INCREMENT NOT NULL,
role VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
password VARCHAR(40) NOT NULL,
PRIMARY KEY (id)
) AUTO_INCREMENT = 1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;