CREATE DATABASE monitorsensors;
\c monitorsensors;

CREATE TABLE IF NOT EXISTS TYPE (
type VARCHAR(30) NOT NULL,
PRIMARY KEY (type)
);

INSERT INTO TYPE (type) VALUES ('Pressure'), ('Voltage'), ('Temperature'), ('Humidity');

CREATE TABLE IF NOT EXISTS UNIT (
unit VARCHAR(30) NOT NULL,
PRIMARY KEY (unit)
);

INSERT INTO UNIT (unit) VALUES ('bar'), ('voltage'), ('°С'), ('%');

CREATE TABLE IF NOT EXISTS SENSORS (
id  BIGSERIAL NOT NULL,
title VARCHAR(30) NOT NULL,
model VARCHAR(15) NOT NULL,
range_from INT NOT NULL,
range_to INT NOT NULL,
type VARCHAR(30) NOT NULL,
unit VARCHAR(30),
location VARCHAR(10),
description VARCHAR(200),

PRIMARY KEY (id),
FOREIGN KEY (type) REFERENCES TYPE (type),
FOREIGN KEY (unit) REFERENCES UNIT (unit)
);

CREATE TABLE IF NOT EXISTS USERS (
id BIGSERIAL NOT NULL,
role VARCHAR(20) NOT NULL,
state VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL,
password VARCHAR(80) NOT NULL,
PRIMARY KEY (id)
);